apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "store-api"
  title: "Store API"
  description: "Backend of Store"
  tags:
    - go
  links:
    - url: http://dashboard.com
      title: Dashboard
      icon: dashboard
    
spec:
  type: service
  lifecycle: production
  owner: "team-backend"
  provideApis:
    - priceApi
    - itemsApi
  system: shop
  # if kind API
  # definition:
  #   $text: https://github.com/APIs-guru/openapi-directory/blob/main/APIs/archive.org/search/1.0.0/openapi.yaml
