apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "store-api"
  title: "Store API"
  description: "Backend of Store"
  tags:
    - go
  links:
    - url: http://dashboard.com
      title: Dashboard
      icon: dashboard
    
  annotations:
    github.com/project-slug: oliverwehrens/backstage-io-demo-catalog
    backstage.io/techdocs-ref: dir:./backend-api/
spec:
  type: service
  lifecycle: production
  owner: "team-backend"
  provideApis:
    - priceApi
    - itemsApi
  system: shop
